// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/mcp-server/generate-tools-from-openapi.mjs

const { z } = require('zod');

/**
 * @param {import('@modelcontextprotocol/sdk/server/mcp.js').McpServer} server
 * @param {{ sfRequest: (method: string, url: string, options: any) => Promise<any>, safeJsonStringify: (v:any)=>string, SF_BACKEND: string }} helpers
 */
function registerGeneratedTools(server, helpers) {
  const { sfRequest, safeJsonStringify, SF_BACKEND } = helpers;

  server.tool(
    "create",
    "POST /api/jobs",
    {
      body: z.any(),
    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/jobs".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/jobs` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("POST", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );

  server.tool(
    "list",
    "GET /api/jobs/{jobId}/parts-reservations",
    {
      jobId: z.number().int(),
    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/jobs/{jobId}/parts-reservations".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/jobs/${jobId}/parts-reservations` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("GET", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );

  server.tool(
    "create_1",
    "POST /api/jobs/{jobId}/parts-reservations",
    {
      jobId: z.number().int(),
      body: z.any(),
    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/jobs/{jobId}/parts-reservations".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/jobs/${jobId}/parts-reservations` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("POST", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );

  server.tool(
    "listTechnicians",
    "GET /api/technicians",
    {

    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/technicians".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/technicians` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("GET", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );

  server.tool(
    "listJobs",
    "GET /api/technicians/{technicianId}/jobs",
    {
      technicianId: z.number().int(),
      from: z.string().optional(),
      to: z.string().optional(),
    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/technicians/{technicianId}/jobs".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/technicians/${technicianId}/jobs` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("GET", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );

  server.tool(
    "listParts",
    "GET /api/parts",
    {

    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/parts".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/parts` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("GET", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );

  server.tool(
    "cancel",
    "DELETE /api/jobs/{jobId}/parts-reservations/{reservationId}",
    {
      jobId: z.number().int(),
      reservationId: z.number().int(),
    },
    async (args) => {

      const query = new URLSearchParams();
      for (const [k, v] of Object.entries(args)) {
        if (v === undefined || v === null) continue;
        if (k === 'body') continue;
        // skip path params (already interpolated)
        if ("/api/jobs/{jobId}/parts-reservations/{reservationId}".includes('{' + k + '}')) continue;
        query.set(k, String(v));
      }
      const url = `${SF_BACKEND}/api/jobs/${jobId}/parts-reservations/${reservationId}` + (query.toString() ? ('?' + query.toString()) : '');


      const resp = await sfRequest("DELETE", url, {
        headers: { 'Content-Type': 'application/json' },
        data: args.body,
      });

      if (resp.status >= 200 && resp.status < 300) {
        return { content: [{ type: 'text', text: safeJsonStringify(resp.data) }] };
      }
      return { isError: true, content: [{ type: 'text', text: 'Backend error (' + resp.status + '): ' + safeJsonStringify(resp.data) }] };

    }
  );
}

module.exports = { registerGeneratedTools };
